### ISSUE TITLE
[Question] Is support for RP2040 coming?

### ISSUE THREAD

**Issue by Roming22** [felias-fogg/SingleWireSerial#2]
I have a project with 2 boards using RP2040 controllers, connected by 3 wires (power, ground, and data).
I need to pass data back and forth the 2 boards, which requires a half-duplex protocol.

I suppose this library has some sort of synchronization mechanism to make sure the board is ready to receive data on the listening end.

Would this project be the right fit? If not do you know of another library that would fit the bill?

**Comment by felias-fogg** [comment]
Hi,

this project is definitely not made for RP2040 since it makes heavy use of low level features of the AVR MCUs and currently there are no plans to port it to RP2040.

The synchronization must take place on a higher level of your communication protocol. That is, if you have a server and a client, they have to both know when it is time to send or to receive data.
